const initialProducts = [
  {
    id: 1,
    name: 'Arena Sanitaria para Gato Calabaza',
    description: 'Arena aglomerante ultra absorbente con control de olores aroma de lavanda de 25kg.',
    price: 60.000,
    image: require("./images/Arena-Lavanda-25kg-refact.png"),
    category: 'Aseo',
    stock: 15,
  },
  {
    id: 2,
    name: 'Arena Sanitaria para Gato Calabaza',
    description: 'Arena aglomerante ultra absorbente con control de olores aroma de café de 25kg.',
    price: 60.000,
    image: require("./images/Arena-Cafe-25kg-refact.png"),
    category: 'Aseo',
    stock: 15,
  },
    {
    id: 3,
    name: 'Arena Sanitaria para Gato Calabaza',
    description: 'Arena aglomerante ultra absorbente con control de olores aroma de vainilla de 25kg.',
    price: 60.000,
    image: require("./images/Arena-Vainilla-25kg-refact.png"),
    category: 'Aseo',
    stock: 15,
  },
    {
    id: 4,
    name: 'Arena Sanitaria para Gato Calabaza',
    description: 'Arena aglomerante ultra absorbente con control de olores aroma de manzana de 25kg.',
    price: 60.000,
    image: require("./images/Arena-Manzana-25kg-refact3.png"),
    category: 'Aseo',
    stock: 15,
  },
    {
    id: 5,
    name: 'Arena Sanitaria para Gato Calabaza',
    description: 'Arena aglomerante ultra absorbente con control de olores aroma de rosa de 25kg.',
    price: 60.000,
    image: require("./images/Arena-Rosa-25kg-refact.png"),
    category: 'Aseo',
    stock: 15,
  },
    {
    id: 6,
    name: 'Arena Sanitaria para Gato Calabaza',
    description: 'Arena aglomerante ultra absorbente con control de olores aroma de coco con carbón activado de 25kg.',
    price: 67.000,
    image: require("./images/Arena-Carbon-25kg-refact.png"),
    category: 'Aseo',
    stock: 15,
  },
  {
    id: 7,
    name: 'Alimento para gato DonKat',
    description: 'Croquetas balanceadas enriquecidas con vitaminas y minerales de 7kg.',
    price: 68.000,
    image: require('./images/DonKat-7kg-refact.png'),
    category: 'Alimentos',
    stock: 8,
  },
  {
    id: 8,
    name: 'Alimento para gato Monello Salmón',
    description: 'Croquetas balanceadas con sabor a pollo enriquecidas con vitaminas y minerales de 15kg.',
    price: 230.000,
    image: require('./images/Monello-Salmon-15kg-refact.png'),
    category: 'Alimentos',
    stock: 8,
  },
    {
    id: 9,
    name: 'Alimento para gato BR for CAT Gatitos',
    description: 'Croquetas balanceadas enriquecidas con vitaminas y minerales de 3kg.',
    price: 70.000,
    image: require('./images/Brforcat-gaticos-3-kg-refact.png'),
    category: 'Alimentos',
    stock: 8,
  }
];

export default initialProducts;